name: Build sourcepawn and commit

on:
  push:
    paths:
      - '**.sp'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile sourcepawn
        uses: spiretf/spcomp@v0.1
        with:
          source: './plugin/mapdownloader.sp'
          target: './plugin/mapdownloader.smx'

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Compile sourcepawn" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
